### PR TITLE
A topic about car traveling

### PR DESCRIPTION
**Pull request by Waails**
Briefly, Monika tells about what she been imagining, which is about if the player could drive and if they could take her somewhere beautiful, but also speak about the dangers of driving while she tells the player: "if you drive, please, drive safely, okay?".

### CODE REVIEW

**Comment by FireyAmber** [comment]
Alright, I'll tackle this one line by line just like I've done with other PRs:

> m 1a "If you could drive and offer me a car ride and take me somewhere..."

This line should try to cut off the use of "and" a bit. (Pretty much reword it so "and" isn't ussed twice)

>     m 3j "I would love to sit at your side, watching everything through the window..."

Pretty sure this should be "sit by your side".

>     m 3b "Especially when it's just me and you~"
    m 3a "That reminds me."
    m 2a "Sometimes, driving away from home is a good thing to do during vacations."

These 3 lines don't feel like they flow well into each other.

> m 2k "You can meet new places, go to a resort, even meet new friends!"

Meet new places?

>     m 3j "You driving while I stay with you, experiencing those good things at your side~"

This line feels redundant since Monika mentions similar feelings earlier into the topic.

These are some minor mistakes while I feel that there's a bigger issue plaguing this topic; by this I mean that the topic feels really separated into "two sections" that don't flow into each other like a converastion, the first section is where hse talks about how she would like to be with the player while driving and then on the second section she talks about reckless driving. I think this should be rewrite to create a better flow from one section to another so they don't seem that split, aside from avoiding mention redudant information over and over again.

**Comment by Waails** [comment]
Hopefully it's all good, now waiting for other people to review and see if it's all good.

**Comment by Hafizzin** [comment]
Good Idea My intelligent friend!

**Comment by meddysan** [comment]
"Sit at" and "Sit by" are both valid for describing the seating locating. "At" tends to imply a little more immediacy and closeness. Either one is fine.

`        m 1a "If you could drive, so you could offer me a car ride and take me somewhere..."`
Drop the word "so".

Label and things below are too far indented.


I do think the segue from travel to reckless driving is not very smooth.

**Comment by Waails** [comment]
Hopefully this looks good now. The "reckless driving" part would make it kinda worrying to think about so I made it even more positive by taking it out and adding one extra line.

**Comment by Waails** [comment]
Forgot to tell I did another 'fix', so, I will now just wait for the reviews/approval/disapproval

**Comment by kaido1224** [comment]
i just tried to make it flow a little cleaner while keeping your original content as much as I could.

Maybe adjust it be something like:
"[player], I've been daydreaming about something."
"Wouldn't it be nice if you and I could get into a car and just drive somewhere?"
"I'd love to travel to some beautiful far off places that we can explore together."
"Maybe we could drive through a beautiful forest or even across a coastline at sunset."
"I guess it really doesn't matter where we go, [player], as long as I'm with you."
"I'd be happy just to sit by your side, watching everything through the window pass by."
"Checking out new places can be fun, you can discover new things and meet new people."
"This is something I've been think about for awhile now."
"If we could do this together, [player], it would be really fun. Don't you think?"
return

**Comment by Danymations** [comment]
@Waails Great topic, I really like it!
Here were some edits that were made by me and @synnnical 

```
m 1i "[player], something has been on my mind lately..."
m 1a "Wouldn't it be nice to drive somewhere far away, just you and I together?"
m 3k "It'd be lovely to explore some beautiful places, don't you think?"
m 3b "Maybe we could drive through an alluring forest... or even see the sunset by the coastline!"
m 3j "It really doesn't matter where we go, [player], anywhere is perfect as long as I'm with you."
"Just sitting next to you, enjoying the scenery... I'd be the happiest girl in the world."
"Checking out new places, discovering new customs, and meeting new people sounds very fun, don't you think so?"
m 1a "I can't wait until we can do so together. That's just one more reason why I want to escape this world, and see you face to face in your reality."
```

**Comment by monikLover** [comment]
Edited by @synnnical and @Danymations, and reviewed. Approved.

**Pull request merged**
