### PR TITLE
Hungry mood

### PR DESCRIPTION
**Pull request by kaido1224**
Hunger mood topic

### CODE REVIEW

**Comment by ThePotatoGuy** [comment]
Is it intentional to have the screen tear glitch only at the start and not when transitioning back in? Otherwise the transition from glitch back to normal flow is awkward.

**Comment by kaido1224** [comment]
i can add it to the end as well.

**Comment by ThePotatoGuy** [comment]
I would add it to the end, makes it clear its a glitch and that it reverts itself somehow.

**Comment by kaido1224** [comment]
Give me a few minutes and I'll have it fixed. Just wanna test it first.

**Comment by kaido1224** [comment]
OK @ThePotatoGuy I added it and tested it. I'm glad I did because there was a typo in the {cps} statement. It should be good now.

**Pull request merged**
