### PR TITLE
monika_desertbeach

### PR DESCRIPTION
**Pull request by FireyAmber**

### CODE REVIEW

**Comment by juank713** [comment]
"I don't like sand"
-Anaking Skywalker-

**Comment by monikLover** [comment]
@juank713 Please refrain from commenting anything useless in the PRs.

**Comment by chillandgrill** [comment]
Grammatical issues on lines 4808, 4809 and 4810.

**Comment by Winblows2** [comment]
Going off of @chillandgrill's statement, this topic in general is a complete mess. There are multiple grammatical issues, and sentence structure is very poor. 

I couldn't even manage to fix the grammatical issues because there was just *so much* wrong. This doesn't mean @FireyAmber is a bad writer, but I recommend this topic be closed for a complete rewrite. 

If anyone else has a comment to leave on this PR, let me know.

**Comment by monikLover** [comment]
Rejecting due to consensus. Refer to @Winblows2's review. Closing.

**Pull request closed without merging**
