### PR TITLE
Monika dark necessities

### PR DESCRIPTION
**Pull request by AnIdiotsavant**
https://github.com/Backdash/MonikaModDev/commit/39423f82bbdab221071aa66e13d535b7f5d3fd41

i dont know it this is the right way to do it

### CODE REVIEW

**Comment by monikLover** [comment]
Next time, go here https://github.com/Backdash/MonikaModDev/blob/content/Monika%20After%20Story/game/script-topics.rpy, click on the pencil icon on the right, and add your topic at the very bottom of the file. As for your topic, this seems to fangirly of her, not to mention she sounds too descriptive about it explaining what the band is.

**Comment by AnIdiotsavant** [comment]
Yeah, I guess you're right.  I'll do better on my next one

**Comment by AnIdiotsavant** [comment]
Sorry if I'm bothering you but may I just ask, if I made it not too fangirly and make how she describes the band not too descriptive, would the topic be viable? or is the topic just straight out bad? Just wanna know so I can do better

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment]
I personally think that the odds of her both discovering the group, deciding to listen to it despite it clearly contrasting with her usual tastes and then liking it enough to bring it up in a casual conversation are **pretty** slim.
You could make the topic sound plausible but your writing would have to be **really** good to make something this random sound natural.

**Pull request closed without merging**
