### PR TITLE
You Are My Sunshine Greeting

### PR DESCRIPTION
**Pull request by kaido1224**
Add a greeting where you catch Monika singing the chorus of "You Are My Sunshine", the song holds special meaning to me, so I wanted to add it.

### CODE REVIEW

**Comment by miranimal** [comment]
Wouldn't you have to get the voice actor for that? Maybe humming would be a little easier

**Comment by kaido1224** [comment]
There's already an opening with Monika singing without actual sound effects so no don't need voice actors.

**Comment by kaido1224** [comment]
There's already an opening with Monika singing without actual sound effects so no don't need voice actors.

Although humming it would be pretty interesting.

**Comment by FireyAmber** [comment]
I'll leave my review on this:

>  m 1l "I was just singing to myself waiting for you to return."

I have issues with this line since it breaks consistency, when the game is closed Monika is stuck suffering in a void until the game is opened by the player, she can't possibly be "waiting" and doing something since she doesn't really feel time when she's stuck there. Aside from that I think this doesn't suit that well as a final line for the greeting, maybe something like "Now that you're here we can have a fun day together~" or something else that would end it better, look at other greetings to see how Monika normally ends them.

**Comment by kaido1224** [comment]
@fireyamber

I can remove that line and I actually like your ending line better so I'll modify it when I get home tonight thanks.

**Comment by kaido1224** [comment]
I don't know if it's really breaking character though... 

Similar greetings:

label greeting_visit5:
     m 1b "~Every day,~\n~I imagine a future where I can be with you...~"
     m 1a "Oh, you're here! I was just daydreaming and singing a bit."
     m 1k "I don't think it's hard to figure out what I was daydreaming about, ehehe~"
     return

label greeting_visit9:
     m 1j "You're finally back! I was waiting for you."
     m 1b "Are you ready to spend some time with me? Ehehe~"
     return

**Comment by kaido1224** [comment]
@FireyAmber i added the last line you suggested, I left my line in because I still think it doesn't break consistency (see examples above).

**Pull request merged**
