### PR TITLE
Changelog for Pong

### PR DESCRIPTION
**Pull request by ghost**
Added difficulty.
Difficulty determines monika's paddle-movement-cap, the ball's start-speed, max-speed and acceleration. 

Recalibrated monika's paddle-movement-cap, the ball's start-speed, max-speed and acceleration.
Caped the max reflection angle.
Removed walls outside of the field.

Added dialog (Could be adapted to affection, could be randomized).

Includes the pull requests https://github.com/Monika-After-Story/MonikaModDev/pull/3156 and https://github.com/Monika-After-Story/MonikaModDev/pull/3154

### CODE REVIEW

**Comment by dennisOdenbreit** [comment]
I did what the FAQ said.
Granted it did not say much.
So is this not a rebase then?
Do I need to use the git command line to do that?

**Comment by dennisOdenbreit** [comment]
How did the dateline commit get into this pull request?
It has nothing to do with what I was working on...

**Comment by multimokia** [comment]
That commit existed in the `enhancement` branch, which is what your `patch-6` branch here is based on. However it's not in the `content` branch, so it's trying to even it out. You will need to use `git rebase` on the command line to rebase it for this case.

**Comment by dennisOdenbreit** [comment]
Sorry, I don't have enough experience to do this.
I tried using a guide but it did not work and was quite complicated.

There is only 1 file that has to be overridden completly.
This is basically no work or has any complexity in comparison.

Since I can't do it the other way I will use the ui to create a pull-request with the matching base ... i hope.
You will have to reassign the labels then.

**Pull request closed without merging**
