### PR TITLE
Contributions + "Partner" + Cleanup + "Cities" Label.

### PR DESCRIPTION
**Pull request by Rune0n**
Added myself to the contributors list.
Changed the word "partner" to appropriate substitutes, as requested.
Removed incomplete ideas that have been addressed. (Centering around a real girlfriend, which are under the label monika_girlfriend).
Added new label: cities, addressing an incomplete idea.
Deleted relevant idea.

### CODE REVIEW

**Comment by Winblows2** [comment]
@monikLover

**Comment by therationalpi** [comment]
I tried to make the city topic a bit more conversation.

**Comment by therationalpi** [comment]
Hold on, that last edit is bad grammar.

**Comment by Rune0n** [comment]
Oh- is that so? I must have misread. I'll fix that, my apologies.

**Pull request merged**
