### PR TITLE
Otaku topic

### PR DESCRIPTION
**Pull request by Subzerosan**
I'm not really familiar with the cheat sheet. Fill it with whatever expression is appropriate.

### CODE REVIEW

**Comment by Kiosho** [comment]
I swear this topic was already in the script. Just some edits?

**Comment by ThePotatoGuy** [comment]
I just did a search and I didn't find it.

**Comment by Subzerosan** [comment]
Nah man I closed down my previous pull request. That had my otaku topic but it had to be reworked so this is the revision rune approved of.

**Comment by Kiosho** [comment]
Ah I see. I knew I saw this exact bit of dialogue.

**Pull request merged**
