### PR TITLE
Revert "fix crash with dialog"

### PR DESCRIPTION
**Pull request by therationalpi**
Reverts Backdash/MonikaModDev#314

### CODE REVIEW

**Comment by ThePotatoGuy** [comment]
Is there a reason why we need to revert this?

I was able to recreate the crash and `boyfriend` was not defined anywhere.

**Comment by therationalpi** [comment]
Yeah, this was the wrong fix. The correct fix is to make the gender switch on this sentence work. Doing that right now.

**Comment by therationalpi** [comment]
@ThePotatoGuy Okay, so there were two things going on here. The first was that I used the wrong variable: [bf] is defined but [boyfriend] isn't.

The other problem was that Renpy's define statement didn't work the way I expected and the flow for setting gender wasn't being called during startup. I fix that.

**Comment by ThePotatoGuy** [comment]
Checked the fix and it works.

**Pull request merged**
