### PR TITLE
Content Changes

### PR DESCRIPTION
**Pull request by Rune0n**
I've done a rewrite of several sections for quality. Fixes include grammar, word choice, and structure. I've tried to match her original voice as closely as possible when doing these changes.
For conversations where I felt that something was missing, I added a sentence or two in.

### CODE REVIEW

**Comment by therationalpi** [comment]
Look like some nice changes. I'll check them over again later and we can probably squeeze this in the 0.5.1 release.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by therationalpi** [comment]
Can you go back through this and put back some of the contractions and wordy transitions? This is supposed to be conversational speech.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Winblows2** [comment]
Looks good. I'll double check it to make sure.

**Comment by Winblows2** [comment]
Checks out. Merged.

**Pull request merged**
