### PR TITLE
changed masturbation topic

### PR DESCRIPTION
**Pull request by juliathegolden**
changed masturbation topic to be more succinct and less shame-y.

### CODE REVIEW

**Comment by MarkusRamikin** [comment]
Very much an improvement.

**Comment by subnatica** [comment]
ummmmmmmmmmmmmmmmmmmmmmmmmmmm

**Comment by subnatica** [comment]
ok then

**Comment by CommenterOfComments** [comment]
So I remembered this existing after getting the topic again, and I was curious, why was this closed? It seems like they're almost trying to hide their reasoning for just leaving this to dust.

**Pull request closed without merging**
