### PR TITLE
80s synth version of the Main Theme

### PR DESCRIPTION
**Pull request by HalHarrison**
Made this for fun, feel free to use it in the mod however you want.

I already matched the audio level to the other songs.

https://www.dropbox.com/s/q741p62qasf0wsl/DOKI%20DOKI%2080S%20SYNTH%20STYLE.wav?dl=0

### CODE REVIEW

**Comment by HalHarrison** [comment]
Yeah dont know how all those other links got added in :/
Ah well.

**Comment by HalHarrison** [comment]
https://www.online-convert.com/result/d1272024-999b-408a-9e21-0755ef7b68ba
This can convert it to .OGG for better use with the game.
I didnt go ahead and do it myself since I have no clue what bitrate, etc. the game likes.

**Comment by monikLover** [comment]
Sorry but this PR is a mess and might cause problems. Closing.

**Comment by ThePotatoGuy** [comment]
@HalHarrison We'll incorporate it into the mod, but please make it a suggestion/issue next time if you aren't going to implement it yourself.

**Pull request closed without merging**
