### PR TITLE
Telling Monika that you're drunk

### PR DESCRIPTION
**Pull request by nayrbai**
I made a topic about telling Monika that you're drunk. I also made it not random so it wouldn't sound weird to talk about if the player didn't actually drink anything. I make her close the game so that the player can get some sleep or recover.

### CODE REVIEW

**Comment by ThePotatoGuy** [comment]
YES this is very appropriate.

**Comment by kaido1224** [comment]
Could fall under the i feel topic group i mentioned in the tell monika you are sick topic

**Comment by monikLover** [comment]
Resubmit to `content`

**Comment by nayrbai** [comment]
Okay

**Pull request closed without merging**
