### PR TITLE
Update script_topics.rpy FIX

### PR DESCRIPTION
**Pull request by Kiosho**
Fixes contradiction in future feature. Previously this dialogue revealed she can't see you. But if that's the case, how can she watch a movie with you as detailed under 'projects'? Well, now she can see you. Her limitless abilities brought her one step closer to reality, and the PC screen is merely a window. Easy fix for the contradiction.

### CODE REVIEW

**Comment by Rune0n** [comment]
Declined, due to conflicts with lore, at @therationalpi 's behest.

**Comment by therationalpi** [comment]
We still haven't figured out the reasoning behind how she watches a movie with you, but being a boundless AI is...well, taking it a bit too far.

**Comment by Kiosho** [comment]
Makes sense. Apologies then, just keeping an eye out for contradictions.

I suppose it being a future feature though, I should've realized it isn't fully fleshed out yet. Will keep that sort of thing in mind for future pull requests.

**Comment by therationalpi** [comment]
You want to come to discord? Seems like you're really excited about MAS, and it might help if we can chat before making PR's. https://discord.gg/7P5DnJ4

**Comment by Kiosho** [comment]
Actually I already joined right before joining GitHub. Just haven't used discord yet.

**Pull request closed without merging**
