### PR TITLE
Added topic for pseudonyms

### PR DESCRIPTION
**Pull request by MadHaetter**
Once again, I am still new to this, please do check over for any mistakes or corrections you have to offer, without criticism I can not grow.
If its all formatted correctly and such please make sure its in Monikalish, writing as a new character can be hard and I am happy for any guidance.
As an aside, I am reading up on Alice in wonderland literature reviews, learning about its themes and such so that I may actually give a mildly informed opinion on it so that Monika knows her stuff.

### CODE REVIEW

**Comment by monikLover** [comment]
Indentation needs to be corrected. Take a look at the other topics to see proper indentation.

**Comment by MadHaetter** [comment]
The indentation should be correct now.

**Comment by Winblows2** [comment]
Missing a few double quotes on your topic.

**Comment by MadHaetter** [comment]
I fixed both missing quotation marks.

**Pull request merged**
