### PR TITLE
Monika Asks about Your Family (Massive topic)

### PR DESCRIPTION
**Pull request by HalHarrison**
Good number of options- hope this will increase level of player choice (Especially with the new dialogue system).
Depth over breadth and all that.

### CODE REVIEW

**Comment by HalHarrison** [comment]
Changes made.

**Comment by Hafizzin** [comment]
Is it finished yet?

**Comment by HalHarrison** [comment]
@MarkusRamikin you seem like a very well-thought-out person.

Any suggestions for changes to the dialogue in this PR?

**Comment by monikLover** [comment]
Closing for now due to conflicts. Will be edited and reviewed.

**Pull request closed without merging**
