### PR TITLE
Added a greeting where Monika is in her room.

### PR DESCRIPTION
**Pull request by ThePotatoGuy**
This greeting is a special/interactive greeting that requires a few different flows to setup, so I've prefixed it with an "i" to prevent it from being added to the general greeting list.

Flow:
1. When the game launches, there is a 1 in 20th chance that Monika is considered `in her room`. 
2. In that chance, spaceroom is not called and the player is given 2 choices:
  a. Open door
    1. Monika tells player not to barge into her room like that, but forgives them anyway.
    2. Monika does a short bit setting up the spaceroom manually.
  b. Knock
    1. Monika asks who is it.
    2. Player responds.
    3. Monika says to "hold on", and spaceroom occurs.

Hotkey buttons and hotkeys are disabled during this greeting.

To test this greeting, either:
1. Comment out line 422, where the persistent is being set by random chance.
2. Add a line below that, setting that persistent value to True
3. Launch game
OR
1. Be in developer mode.
2. Launch game and open console.
3. Set `persistent.is_monika_in_room = True`
4. Close and relaunch game.

The dialogue and expressions were a bit rushed, so if changes are needed thats totally fine.

### CODE REVIEW

**Comment by Winblows2** [comment]
I ran a full test of the changes submitted & it works perfectly code-wise. My only concern is the expressions & dialogue, which will be reviewed by @monikLover and @Rune0n. 

Until a review is submitted the PR will be kept open & unmerged.

**Comment by monikLover** [comment]
After opening the door, the webm files do not show up.
After knocking, the bg does not show up and leaves a black screen.

**Comment by ThePotatoGuy** [comment]
@monikLover are you using the current build? 

You removed a key persistent this needs when you merged `content` into this.

**Comment by ThePotatoGuy** [comment]
As per received feedback, I've made some changes to the event. Now the `knock` part of the event can happen as a greeting normally, while the `open door` part only happens once. (The option to `open door` is removed after going thru the label). Also Monika's reentry when she's sitting down is slower.

Other than that, the flow is basically the same.

I made some variable adjustments so testing is going to be different:
1. Change line 421 so the odds are `(1,1)`
2. Set `persistent.seen_monika_in_room = True` (To enable Open Door)
3. Relaunch game

**Comment by ThePotatoGuy** [comment]
😢

**Pull request merged**
