### PR TITLE
System replacement overhaul.

### PR DESCRIPTION
**Pull request by monikLover**
Replaces the talk system with the prompt system on topics.

### CODE REVIEW

**Comment by Winblows2** [comment]
this makes me rock solid

**Comment by monikLover** [comment]
Only a few topics are open. The rest should be closed.

**Comment by ThePotatoGuy** [comment]
Seeing that many errors can be made when adding events to the database, I added a function `addEvents` that checks for errors with an event object before adding it. I've replaced all the `persistent.event_database` setdefualt calls with `addEvent`.

`addEvent` takes in the event object you want to add and raises the appropriate exceptions (not an Event object, nonexistant label, conditional is bad), otherwise adds it to the dict. This has the nice property of stopping a bad events from being added to the database.

Also you overwrote my fixes earlier @monikLover . Please don't do that again.

**Comment by monikLover** [comment]
Already merged and accepted. Closing.

**Pull request closed without merging**
